name=DevLab_VEML7700
version=2.1.6
author=Kevin Townsend, Limor Fried, Adafruit Industries
maintainer=UNIT Electronics
sentence=Arduino library for the DevLab VEML7700 sensor
paragraph=DevLab VEML7700 sensor library based on the original Adafruit VEML7700 library.
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_devlab_veml7700_library
architectures=*
depends=Adafruit BusIO, Adafruit SSD1306
